# Generated by Django 4.0.1 on 2022-06-15 14:51

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language')),
                ('description', tinymce.models.HTMLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
    ]
