# Generated by Django 4.0.1 on 2022-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profilelocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='number',
            field=models.SmallIntegerField(default=0, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
