# Generated by Django 4.0.7 on 2022-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_countryindicatordata_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryindicatordata',
            name='info_yesno',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Info (Yes/No)'),
        ),
    ]
