# Generated by Django 4.0.7 on 2022-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_countryindicatordata_info_yesno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryindicatordata',
            name='info_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Info (numeric)'),
        ),
    ]
