# Generated by Django 4.0.7 on 2022-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_countryindicatordata_info_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryindicatordata',
            name='info_longtext',
            field=models.TextField(blank=True, verbose_name='Info (long text)'),
        ),
    ]
